[*] Start mutation process:
   - targets: datasets.GPT_4.Zero_shot.programs.program_027
   - tests: datasets.GPT_4.Zero_shot.tests.test_027
[*] 8 tests passed:
   - datasets.GPT_4.Zero_shot.tests.test_027 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.GPT_4.Zero_shot.programs.program_027: [0.00092 s] killed by test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_027.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot\tests\test_027.py", line 8, in test_multiple_spaces
    assert is_Diff(n) == expected_output
AssertionError

   - [#   2] ROR datasets.GPT_4.Zero_shot.programs.program_027: [0.00100 s] killed by test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_027.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot\tests\test_027.py", line 8, in test_multiple_spaces
    assert is_Diff(n) == expected_output
AssertionError

[*] Mutation score [0.02507 s]: 100.0%
   - all: 2
   - killed: 2 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
