coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_094.py\", line 19, in test_boolean_elements\n \
    \   def test_boolean_elements(self): self.assertEqual(sum_range_list([True, False,\
    \ True], 0, 2), 2)\nAssertionError: 1 != 2\n"
  killer: test_boolean_elements (datasets.GPT_4.Chain_of_thought1.tests.test_094.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Chain_of_thought1.programs.program_094 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_094.py\", line 19, in test_boolean_elements\n \
    \   def test_boolean_elements(self): self.assertEqual(sum_range_list([True, False,\
    \ True], 0, 2), 2)\nAssertionError: -2 != 2\n"
  killer: test_boolean_elements (datasets.GPT_4.Chain_of_thought1.tests.test_094.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ASR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
number_of_tests: 8
targets:
- datasets.GPT_4.Chain_of_thought1.programs.program_094
tests:
- name: datasets.GPT_4.Chain_of_thought1.tests.test_094
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.03164076805114746
  run_tests_with_mutant: 0.0
total_time: 0.03164076805114746
